version: '3.4'

services:
  splitpackage.api:
    image: 192.168.1.24:5000/splitpackage-api-test:0.0.1
  splitpackage.web:
    image: 192.168.1.24:5000/splitpackage-web-test:0.0.1
    build:
      args:
        BUILDWAY: buildtest