version: '3.4'

services:
  splitpackage.api:
    image: 192.168.1.24:5000/splitpackage-api-test
  splitpackage.web:
    image: 192.168.1.24:5000/splitpackage-web-test
    build:
      args:
        BUILDWAY: buildtest