version: '2'
services:
    db:
        volumes:
          - '/var/lib/mysql:/var/lib/mysql'
    web:
        image: 192.168.1.24:5000/splitpackage-web-test:latest
    api:
        image: 192.168.1.24:5000/splitpackage-api-test:latest
        cpu_shares: 200
        mem_limit: "500M"