version: '2'

services:
    db:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    web:
        image: splitpackage-web-dev:latest
        ports:
            - "8069:80"
        depends_on:
            - api
    api:
        image: splitpackage-api-dev:latest
        ports:
            - "8070:80"
        links:
            - db:splitpackage-db
        depends_on:
            - db