// <auto-generated />
using Abp.Authorization;
using Abp.BackgroundJobs;
using Abp.Events.Bus.Entities;
using Abp.Notifications;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using SplitPackage.EntityFrameworkCore;
using System;

namespace SplitPackage.Migrations
{
    [DbContext(typeof(SplitPackageDbContext))]
    [Migration("20180413020024_convert")]
    partial class convert
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SplitPackage.MultiTenancy.Product", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("CreationTime");

                b.Property<long?>("CreatorUserId");

                b.Property<long?>("DeleterUserId");

                b.Property<DateTime?>("DeletionTime");

                b.Property<bool>("IsActive");

                b.Property<bool>("IsDeleted");

                b.Property<DateTime?>("LastModificationTime");

                b.Property<long?>("LastModifierUserId");

                b.Property<string>("ProductName")
                    .IsRequired()
                    .HasMaxLength(200);

                b.Property<string>("AbbreName")
                    .IsRequired()
                    .HasMaxLength(100);

                b.Property<string>("ProductNo")
                    .IsRequired()
                    .HasMaxLength(50);

                b.Property<string>("Sku")
                    .IsRequired()
                    .HasMaxLength(50);

                b.Property<string>("TaxNo")
                    .HasMaxLength(20);

                b.Property<string>("Brand")
                   .HasMaxLength(50);

                b.Property<double>("Weight")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.HasIndex("CreatorUserId")
                    .IsUnique();

                b.HasIndex("DeleterUserId")
                    .IsUnique();

                b.HasIndex("LastModifierUserId")
                    .IsUnique();

                b.ToTable("Products");
            });

            modelBuilder.Entity("SplitPackage.Business.Product", b =>
            {
                b.HasOne("SplitPackage.Authorization.Users.User")
                    .WithOne()
                    .HasForeignKey("SplitPackage.Business.Product", "CreatorUserId");

                b.HasOne("SplitPackage.Authorization.Users.User")
                    .WithOne()
                    .HasForeignKey("SplitPackage.Business.Product", "DeleterUserId");

                b.HasOne("SplitPackage.Authorization.Users.User")
                    .WithOne()
                    .HasForeignKey("SplitPackage.Business.Product", "LastModifierUserId");

                b.HasOne("SplitPackage.MultiTenancy.Tenant")
                    .WithOne()
                    .HasForeignKey("SplitPackage.Business.Product", "TenantId");
            });
#pragma warning restore 612, 618
        }
    }
}
